### ISSUE TITLE
New Generator: Static Daily Entry

### ISSUE THREAD

**Issue by BuJo** [synyx/buchungsstreber#107]
Some daily activities for me are not handled by a calendar entry.

I'd like a configurable generator for that.

```yaml
2022-01-01:
- 0.0 t#7654 Admin Daily Cleanup
```

```yaml
generators:
  daily:
    - activity: Admin
      issue: 7654
      prefix: t
      text: Daily Cleanup
```
