### ISSUE TITLE
Make minimum time entry configurable

### ISSUE THREAD

**Issue by dgrammlich** [synyx/buchungsstreber#20]
Actually the minimum time entry is fix with 0.25, which is 15 minutes. It would be great to make this configurable in the `config.yml`.

A global value would be enough for the first step. The `config.yml` could look like this:

```yaml
timesheet_file: ~/buchungsstreber/buchungen.yml
archive_path: ~/buchungsstreber/archive
hours: 8.0
minimum_time_entry: 0.25
generators:
...
```
