### ISSUE TITLE
`watch` mode shows wrong Redmine color

### ISSUE THREAD

**Issue by dgrammlich** [synyx/buchungsstreber#55]
I've defined a green color for the first Redmine (S), a blue color for the second Redmine (C). The first Redmine is in `watch` mode shown with the default color (red), the second Redmine is shown with the color defined for the first Redmine.

![Screenshot from 2021-01-11 12-09-25](https://user-images.githubusercontent.com/5312377/104173560-4212d700-5406-11eb-96b2-7c643db32c42.png)

```
redmines:
  - 
    name: first Redmine
    prefix: S
    color: '#76b82a'
  -
    name: second Redmine
    prefix: C
    color: '#0082c9'
```

----

Buchungsstreber `2.6.1`
Ubuntu `18.04.5`
Ruby `ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux-gnu]` with
* ncursesw `1.4.10`
* rb-inotify `0.10.1`
